const fs = require('fs')
const path = require('path')
const { execFileSync } = require('child_process')
const { verifyNativeAgent } = require('./verify-agent')

const root = path.resolve(__dirname, '../..')
const version = require('../../package.json').version
if (!/^\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?$/.test(version)) throw new Error('Invalid agent version')
if (process.platform !== 'win32') throw new Error('Native agent release builds require Windows, CMake and Visual Studio C++ Build Tools; see docs/store-agent-beta8.md for cross-compilation checks')
const build = path.join(root, 'agent/build/cmake')
const run = (command, args) => execFileSync(command, args, { cwd: root, stdio: 'inherit', windowsHide: true })
run('cmake', ['-S', 'agent', '-B', build, '-A', 'x64', `-DAGENT_VERSION=${version}`])
run('cmake', ['--build', build, '--config', 'Release', '--parallel', '2'])
run('ctest', ['--test-dir', build, '-C', 'Release', '--output-on-failure'])
const exe = path.join(root, 'agent/build/HyperFamilyStoreAgent.exe')
const result = verifyNativeAgent(exe)
fs.writeFileSync(`${exe}.sha256`, `${result.sha256}  HyperFamilyStoreAgent.exe\n`)
console.log(`Native agent ${version}: ${result.size} bytes; SHA-256 ${result.sha256}`)
console.log(`Inbox Windows DLLs only: ${result.imports.join(', ')}`)
