'use client'

import { Pencil, Trash2, Building2, Link as LinkIcon, Phone } from 'lucide-react'
import { Button, EmptyState } from '@/components/ui'

export default function BranchList({ branches, onEdit, onDelete, onAdd }) {
  if (!branches.length) return <EmptyState icon={<Building2 />} title="No branches" description="Add your first retail branch to begin managing its infrastructure." action={<Button onClick={onAdd}>Add branch</Button>} />
  return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b text-[10px] uppercase tracking-wider text-[rgb(var(--muted))]"><th className="px-4 py-3">Branch</th><th className="px-4 py-3">Network links</th><th className="px-4 py-3">Manager</th><th className="px-4 py-3">Deputy</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{branches.map((branch) => <tr key={branch.id} className="border-b last:border-0 hover:bg-[rgb(var(--border)/.22)]"><td className="px-4 py-4"><b className="block text-sm">{branch.name}</b><span className="mt-1 inline-block rounded bg-[rgb(var(--border)/.55)] px-1.5 py-0.5 font-mono text-[9px]">{branch.code}</span></td><td className="px-4 py-4"><div className="space-y-1">{branch.link1 ? <p className="flex items-center gap-1.5"><LinkIcon size={12} className="text-nord-8" />{branch.link1} <span className="font-mono text-[rgb(var(--muted))]">{branch.ip_link1}</span></p> : '—'}{branch.link2 && <p className="flex items-center gap-1.5"><LinkIcon size={12} className="text-nord-13" />{branch.link2} <span className="font-mono text-[rgb(var(--muted))]">{branch.ip_link2}</span></p>}</div></td><td className="px-4 py-4"><b>{branch.manager_name || '—'}</b>{branch.manager_tell && <p className="mt-1 flex items-center gap-1 text-[rgb(var(--muted))]"><Phone size={11} />{branch.manager_tell}</p>}</td><td className="px-4 py-4"><b>{branch.deputy_name || '—'}</b>{branch.deputy_tell && <p className="mt-1 flex items-center gap-1 text-[rgb(var(--muted))]"><Phone size={11} />{branch.deputy_tell}</p>}</td><td className="px-4 py-4"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" onClick={() => onEdit(branch)} aria-label={`Edit ${branch.name}`}><Pencil size={16} /></Button><Button variant="ghost" size="icon" onClick={() => onDelete(branch)} aria-label={`Delete ${branch.name}`} className="text-nord-11"><Trash2 size={16} /></Button></div></td></tr>)}</tbody></table></div>
}
