'use client'

import { Pencil, Trash2, Cpu, Eye, EyeOff } from 'lucide-react'
import { Button, Badge, EmptyState } from '@/components/ui'

export default function DeviceList({ devices, branches, onEdit, onDelete, onAdd }) {
  const branchMap = Object.fromEntries(branches.map((b) => [b.id, b]))
  if (!devices.length) return <EmptyState icon={<Cpu />} title="No devices" description="Add routers, switches, servers, checkouts, and other branch equipment." action={<Button onClick={onAdd} disabled={!branches.length}>Add device</Button>} />
  return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b text-[10px] uppercase tracking-wider text-[rgb(var(--muted))]"><th className="px-4 py-3">Device</th><th className="px-4 py-3">Branch</th><th className="px-4 py-3">Address</th><th className="px-4 py-3">Model</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Dashboard</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{devices.map((device) => <tr key={device.id} className="border-b last:border-0 hover:bg-[rgb(var(--border)/.22)]"><td className="px-4 py-4"><b className="block text-sm">{device.name || device.device_type}</b><span className="text-[10px] text-[rgb(var(--muted))]">{device.device_type}</span></td><td className="px-4 py-4"><b>{branchMap[device.branch_id]?.name || 'Unknown'}</b><p className="font-mono text-[9px] text-[rgb(var(--muted))]">{branchMap[device.branch_id]?.code}</p></td><td className="px-4 py-4 font-mono">{device.ip}{device.port ? `:${device.port}` : ''}</td><td className="px-4 py-4">{device.model || '—'}</td><td className="px-4 py-4"><Badge status={device.status || 'unknown'}>{device.status || 'unknown'}</Badge></td><td className="px-4 py-4">{device.is_dashboard_visible ? <span className="flex items-center gap-1.5 text-[#66834e]"><Eye size={14} /> Visible</span> : <span className="flex items-center gap-1.5 text-[rgb(var(--muted))]"><EyeOff size={14} /> Hidden</span>}</td><td className="px-4 py-4"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" onClick={() => onEdit(device)} aria-label={`Edit ${device.name}`}><Pencil size={16} /></Button><Button variant="ghost" size="icon" onClick={() => onDelete(device)} aria-label={`Delete ${device.name}`} className="text-nord-11"><Trash2 size={16} /></Button></div></td></tr>)}</tbody></table></div>
}
