'use client'

import { Boxes } from 'lucide-react'
import { Badge, EmptyState } from '@/components/ui'

export default function InventoryTable({ devices }) {
  if (!devices.length) return <EmptyState icon={<Boxes />} title="No matching assets" description="Change the active filters or add devices to your branch directory." />
  return <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="sticky top-0 bg-[rgb(var(--surface))]"><tr className="border-b text-[10px] uppercase tracking-wider text-[rgb(var(--muted))]"><th className="px-4 py-3">Branch</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Device</th><th className="px-4 py-3">IP address</th><th className="px-4 py-3">Model</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">Asset code</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{devices.map((device) => <tr key={device.id} className="border-b last:border-0 hover:bg-[rgb(var(--border)/.22)]"><td className="px-4 py-4"><b>{device.branch_name}</b></td><td className="px-4 py-4"><span className="rounded-md bg-[rgb(var(--primary)/.1)] px-2 py-1 font-bold text-[rgb(var(--primary))]">{device.device_type}</span></td><td className="px-4 py-4"><b>{device.name || '—'}</b>{device.hostname && <p className="mt-1 font-mono text-[9px] text-[rgb(var(--muted))]">{device.hostname}</p>}</td><td className="px-4 py-4 font-mono">{device.ip}{device.port ? `:${device.port}` : ''}</td><td className="px-4 py-4">{device.model || '—'}</td><td className="px-4 py-4">{device.location || '—'}</td><td className="px-4 py-4 font-mono">{device.asset_code || '—'}</td><td className="px-4 py-4"><Badge status={device.status || 'unknown'}>{device.status || 'unknown'}</Badge></td></tr>)}</tbody></table></div>
}
