'use client'

import { useState } from 'react'
import { KeyRound, Activity } from 'lucide-react'
import { toast } from 'sonner'
import { Button, Card, CardHeader, CardTitle, CardDescription, CardContent, Input, Label } from '@/components/ui'
import { getApi } from '@/lib/api'

export default function GeneralSettings({ settings, onSaved }) {
  const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' })
  const [ping, setPing] = useState({ ping_interval: settings.ping_interval || 3, ping_history_count: settings.ping_history_count || 30 })
  const [busy, setBusy] = useState('')
  const changePassword = async (event) => { event.preventDefault(); if (passwords.newPassword.length < 4) return toast.error('New password must contain at least 4 characters'); if (passwords.newPassword !== passwords.confirmPassword) return toast.error('New passwords do not match'); setBusy('password'); try { await getApi().auth.changePassword(passwords); toast.success('Password changed'); setPasswords({ currentPassword: '', newPassword: '', confirmPassword: '' }) } catch (error) { toast.error(error.message) } finally { setBusy('') } }
  const savePing = async (event) => { event.preventDefault(); const normalized = { ping_interval: Math.min(60, Math.max(1, Number(ping.ping_interval))), ping_history_count: Math.min(100, Math.max(10, Number(ping.ping_history_count))) }; setBusy('ping'); try { const next = await getApi().settings.save(normalized); setPing(normalized); onSaved(next); toast.success('Ping settings saved') } catch (error) { toast.error(error.message) } finally { setBusy('') } }
  return <div className="grid gap-5 xl:grid-cols-2">
    <Card><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-nord-15/15 p-2.5 text-nord-15"><KeyRound size={19} /></div><div><CardTitle>Change administrator password</CardTitle><CardDescription>Use at least four characters. A longer passphrase is recommended.</CardDescription></div></div></CardHeader><CardContent><form onSubmit={changePassword} className="space-y-4"><label><Label>Current password</Label><Input type="password" autoComplete="current-password" required value={passwords.currentPassword} onChange={(e) => setPasswords({ ...passwords, currentPassword: e.target.value })} /></label><label><Label>New password</Label><Input type="password" autoComplete="new-password" minLength={4} required value={passwords.newPassword} onChange={(e) => setPasswords({ ...passwords, newPassword: e.target.value })} /></label><label><Label>Confirm new password</Label><Input type="password" autoComplete="new-password" required value={passwords.confirmPassword} onChange={(e) => setPasswords({ ...passwords, confirmPassword: e.target.value })} /></label><Button disabled={busy === 'password'}>{busy === 'password' ? 'Changing…' : 'Change password'}</Button></form></CardContent></Card>
    <Card><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-nord-8/15 p-2.5 text-nord-10"><Activity size={19} /></div><div><CardTitle>Real-time monitoring</CardTitle><CardDescription>Balance freshness with traffic across monitored networks.</CardDescription></div></div></CardHeader><CardContent><form onSubmit={savePing} className="space-y-4"><label><Label>Ping interval (seconds)</Label><Input type="number" min={1} max={60} value={ping.ping_interval} onChange={(e) => setPing({ ...ping, ping_interval: e.target.value })} /><p className="mt-1 text-[10px] text-[rgb(var(--muted))]">Between 1 and 60 seconds. Default: 3.</p></label><label><Label>Chart history points</Label><Input type="number" min={10} max={100} value={ping.ping_history_count} onChange={(e) => setPing({ ...ping, ping_history_count: e.target.value })} /><p className="mt-1 text-[10px] text-[rgb(var(--muted))]">Between 10 and 100 responses. Default: 30.</p></label><Button disabled={busy === 'ping'}>{busy === 'ping' ? 'Saving…' : 'Save monitoring settings'}</Button></form></CardContent></Card>
  </div>
}
