'use client'

import { useState } from 'react'
import { FolderOpen, Shield, Route, Lock } from 'lucide-react'
import { toast } from 'sonner'
import { Button, Card, CardHeader, CardTitle, CardDescription, CardContent, Input, Label } from '@/components/ui'
import { getApi } from '@/lib/api'

export default function VPNSettings({ settings, onSaved }) {
  const [form, setForm] = useState({ vpn_gateway: settings.vpn_gateway || '', vpn_port: settings.vpn_port || 443, vpn_user: settings.vpn_user || '', vpn_pass: settings.vpn_pass || '', openvpn_path: settings.openvpn_path || '', openvpn_config: settings.openvpn_config || '' })
  const browse = async (key, filters) => { const path = await getApi().dialog.selectFile({ title: key === 'openvpn_path' ? 'Select OpenVPN executable' : 'Select OpenVPN configuration', filters }); if (path) setForm({ ...form, [key]: path }) }
  const save = async (event) => { event.preventDefault(); try { const next = await getApi().settings.save({ ...form, vpn_port: Number(form.vpn_port) }); onSaved(next); toast.success('VPN configuration encrypted and saved') } catch (error) { toast.error(error.message) } }
  return <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Shield size={19} />FortiClient SSL VPN</CardTitle><CardDescription>Full VPN uses the installed FortiClient CLI. Split tunnel uses a reviewed OpenVPN profile with private routes.</CardDescription></CardHeader><CardContent><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-[1fr_140px]"><label><Label>Remote gateway</Label><Input placeholder="vpn.example.com" value={form.vpn_gateway} onChange={(e) => setForm({ ...form, vpn_gateway: e.target.value })} /></label><label><Label>Port</Label><Input type="number" min={1} max={65535} value={form.vpn_port} onChange={(e) => setForm({ ...form, vpn_port: e.target.value })} /></label></div><div className="grid gap-4 sm:grid-cols-2"><label><Label>Username</Label><Input autoComplete="off" value={form.vpn_user} onChange={(e) => setForm({ ...form, vpn_user: e.target.value })} /></label><label><Label>Password</Label><Input type="password" autoComplete="new-password" value={form.vpn_pass} onChange={(e) => setForm({ ...form, vpn_pass: e.target.value })} /></label></div><fieldset className="rounded-xl border p-4"><legend className="px-2 text-xs font-bold">Split tunnel fallback</legend><div className="space-y-4"><label><Label>OpenVPN executable</Label><div className="flex gap-2"><Input value={form.openvpn_path} onChange={(e) => setForm({ ...form, openvpn_path: e.target.value })} /><Button variant="secondary" size="icon" type="button" onClick={() => browse('openvpn_path', [{ name: 'Windows executable', extensions: ['exe'] }])}><FolderOpen size={17} /></Button></div></label><label><Label>Reviewed .ovpn profile</Label><div className="flex gap-2"><Input value={form.openvpn_config} onChange={(e) => setForm({ ...form, openvpn_config: e.target.value })} /><Button variant="secondary" size="icon" type="button" onClick={() => browse('openvpn_config', [{ name: 'OpenVPN profile', extensions: ['ovpn', 'conf'] }])}><FolderOpen size={17} /></Button></div></label></div></fieldset><Button><Lock size={16} />Encrypt and save VPN settings</Button></form></CardContent></Card>
    <div className="space-y-4"><Card className="p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-nord-13/20 p-2.5 text-[#8b6e1c]"><Route size={19} /></div><div><b className="text-sm">Split tunnel</b><p className="mt-1 text-xs leading-relaxed text-[rgb(var(--muted))]">Only routes declared in the approved OpenVPN profile use the tunnel. The service refuses a profile without <code>route-nopull</code>.</p></div></div></Card><Card className="p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-nord-14/20 p-2.5 text-[#66834e]"><Shield size={19} /></div><div><b className="text-sm">Full VPN</b><p className="mt-1 text-xs leading-relaxed text-[rgb(var(--muted))]">FortiClient controls the system-wide connection. Exact CLI availability depends on the installed enterprise edition.</p></div></div></Card><p className="px-2 text-[10px] leading-relaxed text-[rgb(var(--muted))]">VPN changes can require administrator privileges. Test with your organization’s approved profile before production deployment.</p></div>
  </div>
}
