const path = require('path')
const ExcelJS = require('exceljs')
const { dialog } = require('electron')

const DEVICE_TYPES = ['Router', 'Switch', 'iLO', 'Server', 'NVR', 'AccessPoint', 'Scale', 'Client', 'Checkout', 'POS']
const MAX_SWITCH_PORTS = 48

const BRANCH_HEADERS = [
  'Branch Name', 'Branch Code', 'Warehouse Code', 'Link1', 'IP Link1', 'Link2', 'IP Link2',
  'Manager Name', 'Manager Tell', 'Deputy Name', 'Deputy Tell'
]
const LEGACY_BRANCH_HEADERS = [
  'Name', 'Code', 'Warehouse Code', 'Link1', 'IP Link1', 'Link2', 'IP Link2',
  'Manager Name', 'Manager Tell', 'Deputy Name', 'Deputy Tell'
]

// Retained for importing workbooks generated by earlier application versions.
const DEVICE_HEADERS = [
  'Branch Code', 'Device Type', 'Device Name', 'Model', 'Location', 'IP', 'Port', 'Asset Code',
  'Connection Type', 'Connection Port', 'Hostname', 'User', 'Domain', 'ESXI Version',
  'Software Version', 'Terminal ID', 'Acceptance ID', 'Brand', 'Checkout Number',
  'Serial Number', 'Dashboard'
]
const PORT_HEADERS = ['Branch Code', 'Device Name', 'Device IP', 'Port Number', 'VLAN', 'Status', 'IP', 'Details']

// The canonical value is the legacy Devices-sheet heading used by the parser's
// common field map. Each equipment sheet exposes only fields available in its UI form.
const DEVICE_SHEET_FIELDS = {
  Router: [
    ['Device Name', 'Device Name'], ['Model', 'Model'], ['IP', 'IP'], ['Port', 'Port'], ['Asset Code', 'Asset Code']
  ],
  Switch: [
    ['Device Name', 'Device Name'], ['Model', 'Model'], ['Location', 'Location'], ['IP', 'IP'],
    ['Connection Type', 'Connection Type'], ['Connection Port', 'Connection Port'], ['Asset Code', 'Asset Code']
  ],
  iLO: [
    ['Device Name', 'Device Name'], ['IP', 'IP'], ['ESXI Version', 'ESXI Version'], ['Server Model', 'Model'], ['Asset Code', 'Asset Code']
  ],
  Server: [
    ['Device Name', 'Device Name'], ['Hostname', 'Hostname'], ['IP', 'IP']
  ],
  NVR: [
    ['Device Name', 'Device Name'], ['IP', 'IP'], ['Model', 'Model'], ['Asset Code', 'Asset Code']
  ],
  AccessPoint: [
    ['Device Name', 'Device Name'], ['Model', 'Model'], ['Location', 'Location'], ['IP', 'IP'], ['Port', 'Port'], ['Asset Code', 'Asset Code']
  ],
  Scale: [
    ['Device Name', 'Device Name'], ['Model', 'Model'], ['Location', 'Location'], ['IP', 'IP'],
    ['Serial Number', 'Serial Number'], ['Asset Code', 'Asset Code']
  ],
  Client: [
    ['Device Name', 'Device Name'], ['Hostname', 'Hostname'], ['User', 'User'], ['IP', 'IP'], ['Domain', 'Domain']
  ],
  Checkout: [
    ['Device Name', 'Device Name'], ['Checkout Number', 'Checkout Number'], ['Hostname', 'Hostname'], ['IP', 'IP']
  ],
  POS: [
    ['Device Name', 'Device Name'], ['Checkout Number', 'Checkout Number'], ['Brand', 'Brand'], ['Model', 'Model'],
    ['Software Version', 'Software Version'], ['IP', 'IP'], ['Terminal ID', 'Terminal ID'],
    ['Acceptance ID', 'Acceptance ID'], ['Asset Code', 'Asset Code']
  ]
}

const fieldMap = {
  'Device Name': 'name',
  Model: 'model',
  Location: 'location',
  IP: 'ip',
  Port: 'port',
  'Asset Code': 'asset_code',
  'Connection Type': 'connection_type',
  'Connection Port': 'connection_port',
  Hostname: 'hostname',
  User: 'user',
  Domain: 'domain',
  'ESXI Version': 'esxi_version',
  'Software Version': 'version',
  'Terminal ID': 'terminal_id',
  'Acceptance ID': 'acceptance_id',
  Brand: 'brand',
  'Checkout Number': 'checkout_number',
  'Serial Number': 'serial_number'
}

function switchPortHeaders() {
  const headers = []
  for (let number = 1; number <= MAX_SWITCH_PORTS; number += 1) {
    headers.push(
      `Port ${number} Number`,
      `Port ${number} VLAN`,
      `Port ${number} Status`,
      `Port ${number} IP`,
      `Port ${number} Details`
    )
  }
  return headers
}

function deviceSheetHeaders(type) {
  const headers = ['Branch Code', ...DEVICE_SHEET_FIELDS[type].map(([header]) => header), 'Dashboard']
  if (type === 'Switch') headers.push(...switchPortHeaders())
  return headers
}

function clean(value) { return String(value || 'All').replace(/[^a-z0-9_-]/gi, '_') }
function matchesQuery(device, query) {
  if (!query) return true
  const needle = String(query).toLowerCase()
  const values = [
    device.name, device.hostname, device.ip, device.port, device.model, device.asset_code, device.serial_number,
    device.location, device.connection_type, device.connection_port, device.esxi_version, device.version,
    device.user, device.domain, device.checkout_number, device.brand, device.terminal_id, device.acceptance_id,
    device.branch_name, device.branch_code, device.branch_warehouse_code,
    ...(device.switch_ports || []).flatMap((port) => [port.port_number, port.vlan, port.status, port.ip, port.details])
  ]
  return values.some((value) => String(value || '').toLowerCase().includes(needle))
}
function formatSwitchPorts(ports = []) {
  return ports.map((port) => {
    const details = [`Port ${port.port_number}`, port.vlan && `VLAN ${port.vlan}`, port.status, port.ip, port.details].filter(Boolean)
    return details.join(' · ')
  }).join('; ')
}

function valueOf(cellValue) {
  if (cellValue === null || cellValue === undefined) return ''
  if (typeof cellValue === 'object') {
    if (Object.prototype.hasOwnProperty.call(cellValue, 'result')) return valueOf(cellValue.result)
    if (Object.prototype.hasOwnProperty.call(cellValue, 'text')) return String(cellValue.text).trim()
    if (Array.isArray(cellValue.richText)) return cellValue.richText.map((item) => item.text || '').join('').trim()
    if (Object.prototype.hasOwnProperty.call(cellValue, 'hyperlink')) return String(cellValue.text || cellValue.hyperlink || '').trim()
  }
  return String(cellValue).trim()
}

function isValidHost(value) {
  if (!value) return false
  if (/^(?=.{1,253}$)(?!-)(?:[A-Za-z0-9-]{1,63}\.)*[A-Za-z0-9-]{1,63}$/.test(value)) return true
  const parts = value.split('.')
  return parts.length === 4 && parts.every((part) => /^\d+$/.test(part) && Number(part) >= 0 && Number(part) <= 255)
}

function styleSheet(worksheet, widths = {}) {
  worksheet.views = [{ state: 'frozen', ySplit: 1, xSplit: Math.min(2, worksheet.columnCount) }]
  worksheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: worksheet.columnCount } }
  worksheet.getRow(1).height = 28
  worksheet.getRow(1).eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF5E81AC' } }
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true }
    cell.border = { bottom: { style: 'thin', color: { argb: 'FF4C566A' } } }
  })
  worksheet.columns.forEach((column) => {
    const header = valueOf(column.header)
    column.width = widths[header] || (/Details$/.test(header) ? 24 : /Status$|Dashboard/.test(header) ? 13 : /Branch Code|Device Name|Hostname|Model|Location|Asset/.test(header) ? 20 : 16)
  })
}

function addListValidation(worksheet, header, values, lastRow = 501) {
  const headerCell = worksheet.getRow(1).values.findIndex((value) => valueOf(value).toLowerCase() === header.toLowerCase())
  if (headerCell < 1) return
  for (let row = 2; row <= lastRow; row += 1) {
    worksheet.getCell(row, headerCell).dataValidation = {
      type: 'list', allowBlank: true, formulae: [`"${values.join(',')}"`],
      showErrorMessage: true, errorTitle: 'Choose a listed value', error: `Allowed values: ${values.join(', ')}`
    }
  }
}

function addWholeNumberValidation(worksheet, header, minimum, maximum, lastRow = 501) {
  const headerCell = worksheet.getRow(1).values.findIndex((value) => valueOf(value).toLowerCase() === header.toLowerCase())
  if (headerCell < 1) return
  for (let row = 2; row <= lastRow; row += 1) {
    worksheet.getCell(row, headerCell).dataValidation = {
      type: 'whole', operator: 'between', allowBlank: true, formulae: [minimum, maximum],
      showErrorMessage: true, errorTitle: 'Invalid number', error: `Enter a whole number from ${minimum} through ${maximum}`
    }
  }
}

function createInstructionsSheet(workbook) {
  const sheet = workbook.addWorksheet('Instructions', { properties: { tabColor: { argb: 'FF88C0D0' } } })
  sheet.columns = [{ key: 'step', width: 6 }, { key: 'topic', width: 25 }, { key: 'instruction', width: 112 }]
  sheet.addRow(['Step', 'Topic', 'Instruction'])
  const instructions = [
    [1, 'Branches first', 'Enter every location in Branches. Branch Code and Warehouse Code must each be unique. Branch Name, Branch Code, and Warehouse Code are required.'],
    [2, 'Equipment sheets', `Use the dedicated Router, Switch, iLO, Server, NVR, AccessPoint, Scale, Client, Checkout, or POS sheet. Each sheet contains only fields available for that equipment type.`],
    [3, 'Branch association', 'Every equipment row requires Branch Code. It must exactly match a Branch Code in this workbook or an existing application branch.'],
    [4, 'Required equipment fields', 'Branch Code, Device Name, and IP are required on every equipment row. IP may be an IPv4 address or hostname.'],
    [5, 'Dashboard', 'Choose Show to monitor and display the equipment on Dashboard, or Hide to keep it only in the directory. Blank is treated as Hide.'],
    [6, 'One Router', 'Each branch can contain at most one Router. A Router row updates the existing Router for the same Branch Code.'],
    [7, 'Switch ports', `The Switch sheet includes ${MAX_SWITCH_PORTS} explicit port groups in each row. Define no more than ${MAX_SWITCH_PORTS} unique Port Numbers from 1 through ${MAX_SWITCH_PORTS}. Port Status options are Up, Down, or Disabled.`],
    [8, 'Updates', 'Router rows match by Branch Code. Other equipment rows match by Branch Code + equipment type + IP. Matching records are updated; other rows are added.'],
    [9, 'Atomic import', 'The workbook is validated before it changes data. If any row is invalid, nothing is imported and the reported rows must be corrected.'],
    [10, 'Do not rename headers', 'Keep worksheet names and row-1 column headings unchanged. Blank equipment sheets are valid and should remain in the workbook.']
  ]
  instructions.forEach((row) => sheet.addRow(row))
  styleSheet(sheet)
  sheet.getColumn(3).alignment = { vertical: 'top', wrapText: true }
  for (let row = 2; row <= sheet.rowCount; row += 1) sheet.getRow(row).height = 38
  return sheet
}

function createBranchesSheet(workbook) {
  const sheet = workbook.addWorksheet('Branches', { properties: { tabColor: { argb: 'FFA3BE8C' } } })
  sheet.columns = BRANCH_HEADERS.map((header) => ({ header, key: header }))
  styleSheet(sheet, { 'Branch Name': 24, 'Branch Code': 18, 'Warehouse Code': 20, 'Manager Name': 22, 'Manager Tell': 20, 'Deputy Name': 22, 'Deputy Tell': 20 })
  return sheet
}

function createEquipmentSheet(workbook, type) {
  const headers = deviceSheetHeaders(type)
  const sheet = workbook.addWorksheet(type, { properties: { tabColor: { argb: type === 'Switch' ? 'FFB48EAD' : 'FF81A1C1' } } })
  sheet.columns = headers.map((header) => ({ header, key: header }))
  styleSheet(sheet)
  addListValidation(sheet, 'Dashboard', ['Show', 'Hide'])
  for (const header of headers.filter((item) => / Status$/.test(item))) addListValidation(sheet, header, ['Up', 'Down', 'Disabled'])
  for (const header of headers.filter((item) => / Number$/.test(item) && /^Port /.test(item))) addWholeNumberValidation(sheet, header, 1, MAX_SWITCH_PORTS)
  if (headers.includes('Port')) addWholeNumberValidation(sheet, 'Port', 1, 65535)
  return sheet
}

async function chooseSavePath(defaultPath) {
  const result = await dialog.showSaveDialog({
    title: 'Save HyperFamily Excel file',
    defaultPath,
    filters: [{ name: 'Excel Workbook', extensions: ['xlsx'] }]
  })
  return result.canceled ? null : result.filePath
}

async function chooseImportPath() {
  const result = await dialog.showOpenDialog({
    title: 'Import HyperFamily directory',
    properties: ['openFile'],
    filters: [{ name: 'Excel Workbook', extensions: ['xlsx'] }]
  })
  return result.canceled ? null : result.filePaths[0]
}

async function createImportTemplate(database, outputPath = null, actor = 'Admin') {
  const selectedPath = outputPath || await chooseSavePath('HyperFamily-Import-Template.xlsx')
  if (!selectedPath) return { canceled: true }
  const filePath = path.extname(selectedPath).toLowerCase() === '.xlsx' ? selectedPath : `${selectedPath}.xlsx`

  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'HyperFamily Branch Monitor'
  workbook.created = new Date()
  workbook.modified = new Date()
  workbook.properties.subject = 'Branch and type-specific equipment import template'
  createInstructionsSheet(workbook)
  createBranchesSheet(workbook)
  DEVICE_TYPES.forEach((type) => createEquipmentSheet(workbook, type))
  await workbook.xlsx.writeFile(filePath)
  database?.audit(actor, 'IMPORT_TEMPLATE_EXPORT', filePath, `${DEVICE_TYPES.length} equipment sheets with ${MAX_SWITCH_PORTS} Switch port groups`)
  return { success: true, path: filePath }
}

function readSheetRows(worksheet, requiredHeaders, errors, options = {}) {
  const required = options.required !== false
  if (!worksheet) {
    if (required) errors.push(`Missing required worksheet "${options.sheetName || 'Unknown'}"`)
    return []
  }

  const indexes = {}
  worksheet.getRow(1).eachCell({ includeEmpty: true }, (cell, columnNumber) => {
    const header = valueOf(cell.value).toLowerCase()
    if (header && !indexes[header]) indexes[header] = columnNumber
  })
  for (const header of requiredHeaders) {
    if (!indexes[header.toLowerCase()]) errors.push(`${worksheet.name}: missing column "${header}"`)
  }
  if (requiredHeaders.some((header) => !indexes[header.toLowerCase()])) return []

  const rows = []
  for (let rowNumber = 2; rowNumber <= worksheet.rowCount; rowNumber += 1) {
    const values = {}
    let populated = false
    for (const header of requiredHeaders) {
      values[header] = valueOf(worksheet.getCell(rowNumber, indexes[header.toLowerCase()]).value)
      if (values[header]) populated = true
    }
    if (populated) rows.push({ rowNumber, values, sheetName: worksheet.name })
  }
  return rows
}

function readTypedDeviceRows(workbook, errors) {
  const rows = []
  for (const type of DEVICE_TYPES) {
    const headers = deviceSheetHeaders(type)
    const typedRows = readSheetRows(workbook.getWorksheet(type), headers, errors, { sheetName: type })
    for (const row of typedRows) {
      const values = { 'Branch Code': row.values['Branch Code'], 'Device Type': type, Dashboard: row.values.Dashboard }
      for (const [header, canonical] of DEVICE_SHEET_FIELDS[type]) values[canonical] = row.values[header]
      rows.push({ ...row, values, typedValues: row.values })
    }
  }
  return rows
}

function parseDashboard(value, rowLabel, errors) {
  if (!value) return 0
  const normalized = value.toLowerCase()
  if (['show', 'yes', 'true', '1'].includes(normalized)) return 1
  if (['hide', 'no', 'false', '0'].includes(normalized)) return 0
  errors.push(`${rowLabel}: Dashboard must be Show or Hide`)
  return 0
}

function parseSwitchPortValues(values, rowLabel, errors) {
  const numberText = values.number
  const populated = [values.number, values.vlan, values.status, values.ip, values.details].some(Boolean)
  if (!populated) return null
  const portNumber = Number(numberText)
  if (!numberText || !Number.isInteger(portNumber) || portNumber < 1 || portNumber > MAX_SWITCH_PORTS) {
    errors.push(`${rowLabel}: Switch Port Number must be a whole number from 1 through ${MAX_SWITCH_PORTS}`)
    return null
  }
  const status = (values.status || 'Up').toLowerCase()
  if (!['up', 'down', 'disabled'].includes(status)) errors.push(`${rowLabel}: Switch port ${portNumber} Status must be Up, Down, or Disabled`)
  if (values.ip && !isValidHost(values.ip)) errors.push(`${rowLabel}: Switch port ${portNumber} IP is invalid`)
  return {
    port_number: portNumber,
    vlan: values.vlan || null,
    status: ['up', 'down', 'disabled'].includes(status) ? status : 'up',
    ip: values.ip || null,
    details: values.details || null
  }
}

function parseTypedSwitchPorts(row, rowLabel, errors) {
  const ports = []
  const seen = new Set()
  for (let group = 1; group <= MAX_SWITCH_PORTS; group += 1) {
    const port = parseSwitchPortValues({
      number: row.typedValues[`Port ${group} Number`],
      vlan: row.typedValues[`Port ${group} VLAN`],
      status: row.typedValues[`Port ${group} Status`],
      ip: row.typedValues[`Port ${group} IP`],
      details: row.typedValues[`Port ${group} Details`]
    }, `${rowLabel}, port group ${group}`, errors)
    if (!port) continue
    if (seen.has(port.port_number)) errors.push(`${rowLabel}: Switch Port Number ${port.port_number} is duplicated`)
    else {
      seen.add(port.port_number)
      ports.push(port)
    }
  }
  return ports
}

async function parseImportWorkbook(filePath) {
  const workbook = new ExcelJS.Workbook()
  await workbook.xlsx.readFile(filePath)
  const errors = []

  const legacyDevicesSheet = workbook.getWorksheet('Devices')
  const legacyLayout = Boolean(legacyDevicesSheet)
  const branchHeaders = legacyLayout ? LEGACY_BRANCH_HEADERS : BRANCH_HEADERS
  const branchRows = readSheetRows(workbook.getWorksheet('Branches'), branchHeaders, errors, { sheetName: 'Branches' })
  const deviceRows = legacyLayout
    ? readSheetRows(legacyDevicesSheet, DEVICE_HEADERS, errors, { sheetName: 'Devices' })
    : readTypedDeviceRows(workbook, errors)
  const portRows = legacyLayout && workbook.getWorksheet('Switch Ports')
    ? readSheetRows(workbook.getWorksheet('Switch Ports'), PORT_HEADERS, errors, { sheetName: 'Switch Ports' })
    : []

  if (!branchRows.length && !deviceRows.length) errors.push('The workbook does not contain any populated Branch or equipment rows')

  const branches = []
  const branchCodes = new Set()
  const warehouseCodes = new Set()
  for (const row of branchRows) {
    const rowLabel = `Branches row ${row.rowNumber}`
    const branchName = row.values['Branch Name'] || row.values.Name
    const code = row.values['Branch Code'] || row.values.Code
    const warehouseCode = row.values['Warehouse Code']
    if (!branchName) errors.push(`${rowLabel}: Branch Name is required`)
    if (!code) errors.push(`${rowLabel}: Branch Code is required`)
    else if (!/^[A-Za-z0-9_-]{2,20}$/.test(code)) errors.push(`${rowLabel}: Branch Code must use 2-20 letters, numbers, dashes, or underscores`)
    if (!warehouseCode) errors.push(`${rowLabel}: Warehouse Code is required`)
    else if (!/^[A-Za-z0-9_-]{1,40}$/.test(warehouseCode)) errors.push(`${rowLabel}: Warehouse Code must use up to 40 letters, numbers, dashes, or underscores`)
    const codeKey = code.toLowerCase()
    const warehouseKey = warehouseCode.toLowerCase()
    if (code && branchCodes.has(codeKey)) errors.push(`${rowLabel}: Branch Code "${code}" is duplicated in this workbook`)
    if (warehouseCode && warehouseCodes.has(warehouseKey)) errors.push(`${rowLabel}: Warehouse Code "${warehouseCode}" is duplicated in this workbook`)
    if (code) branchCodes.add(codeKey)
    if (warehouseCode) warehouseCodes.add(warehouseKey)
    for (const header of ['IP Link1', 'IP Link2']) if (row.values[header] && !isValidHost(row.values[header])) errors.push(`${rowLabel}: ${header} is invalid`)

    branches.push({
      name: branchName, code, warehouse_code: warehouseCode,
      link1: row.values.Link1, ip_link1: row.values['IP Link1'], link2: row.values.Link2, ip_link2: row.values['IP Link2'],
      manager_name: row.values['Manager Name'], manager_tell: row.values['Manager Tell'],
      deputy_name: row.values['Deputy Name'], deputy_tell: row.values['Deputy Tell']
    })
  }

  const devices = []
  const deviceKeys = new Set()
  const routerBranches = new Set()
  for (const row of deviceRows) {
    const rowLabel = `${row.sheetName} row ${row.rowNumber}`
    const type = row.values['Device Type']
    const branchCode = row.values['Branch Code']
    const deviceName = row.values['Device Name']
    const ip = row.values.IP
    if (!branchCode) errors.push(`${rowLabel}: Branch Code is required`)
    if (!DEVICE_TYPES.includes(type)) errors.push(`${rowLabel}: Device Type must be one of ${DEVICE_TYPES.join(', ')}`)
    if (!deviceName) errors.push(`${rowLabel}: Device Name is required`)
    if (!ip || !isValidHost(ip)) errors.push(`${rowLabel}: IP must be a valid IPv4 address or hostname`)

    if (type === 'Router' && branchCode) {
      const routerKey = branchCode.toLowerCase()
      if (routerBranches.has(routerKey)) errors.push(`${rowLabel}: only one Router can be defined for Branch Code "${branchCode}"`)
      routerBranches.add(routerKey)
    }

    const deviceKey = type === 'Router'
      ? `${branchCode.toLowerCase()}::router`
      : `${branchCode.toLowerCase()}::${type.toLowerCase()}::${ip.toLowerCase()}`
    if (branchCode && type && ip && deviceKeys.has(deviceKey)) errors.push(`${rowLabel}: this device is duplicated in the workbook`)
    if (branchCode && type && ip) deviceKeys.add(deviceKey)

    const device = { branch_code: branchCode, device_type: type, is_dashboard_visible: parseDashboard(row.values.Dashboard, rowLabel, errors), switch_ports: [] }
    for (const [header, key] of Object.entries(fieldMap)) device[key] = row.values[header] || null

    if (row.values.Port) {
      const port = Number(row.values.Port)
      if (!Number.isInteger(port) || port < 1 || port > 65535) errors.push(`${rowLabel}: Port must be a whole number from 1 through 65535`)
      else device.port = port
    }
    if (row.values['Checkout Number']) {
      const checkout = Number(row.values['Checkout Number'])
      if (!Number.isInteger(checkout) || checkout < 1) errors.push(`${rowLabel}: Checkout Number must be a positive whole number`)
      else device.checkout_number = checkout
    }
    if (type === 'Switch' && !legacyLayout) device.switch_ports = parseTypedSwitchPorts(row, rowLabel, errors)
    devices.push(device)
  }

  if (legacyLayout) {
    const switches = new Map(devices.filter((device) => device.device_type === 'Switch').map((device) => [`${device.branch_code.toLowerCase()}::${device.ip.toLowerCase()}`, device]))
    const seenPorts = new Map()
    for (const row of portRows) {
      const rowLabel = `Switch Ports row ${row.rowNumber}`
      const key = `${row.values['Branch Code'].toLowerCase()}::${row.values['Device IP'].toLowerCase()}`
      const target = switches.get(key)
      if (!target) {
        errors.push(`${rowLabel}: no Switch row matches Branch Code "${row.values['Branch Code']}" and Device IP "${row.values['Device IP']}"`)
        continue
      }
      if (target.switch_ports.length >= MAX_SWITCH_PORTS) {
        errors.push(`${rowLabel}: a Switch can contain at most ${MAX_SWITCH_PORTS} ports`)
        continue
      }
      const port = parseSwitchPortValues({
        number: row.values['Port Number'], vlan: row.values.VLAN, status: row.values.Status,
        ip: row.values.IP, details: row.values.Details
      }, rowLabel, errors)
      if (!port) continue
      if (!seenPorts.has(key)) seenPorts.set(key, new Set())
      if (seenPorts.get(key).has(port.port_number)) errors.push(`${rowLabel}: Switch Port Number ${port.port_number} is duplicated for this Switch`)
      else {
        seenPorts.get(key).add(port.port_number)
        target.switch_ports.push(port)
      }
    }
  }

  if (errors.length) throw new Error(`Excel import validation failed:\n• ${errors.slice(0, 30).join('\n• ')}${errors.length > 30 ? `\n• …and ${errors.length - 30} more errors` : ''}`)
  return { branches, devices, layout: legacyLayout ? 'legacy' : 'type-specific' }
}

async function importDirectory(database, inputPath = null, actor = 'Admin') {
  const filePath = inputPath || await chooseImportPath()
  if (!filePath) return { canceled: true }
  const payload = await parseImportWorkbook(filePath)
  const result = database.importDirectory(payload, actor)
  return { ...result, path: filePath, layout: payload.layout }
}

async function exportInventory(database, filters = {}, outputPath = null) {
  let rows = database.listInventory()
  if (filters.branch && filters.branch !== 'all') rows = rows.filter((row) => String(row.branch_id) === String(filters.branch))
  if (filters.type && filters.type !== 'all') rows = rows.filter((row) => row.device_type === filters.type)
  if (filters.query) rows = rows.filter((row) => matchesQuery(row, filters.query))

  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'HyperFamily Branch Monitor'
  workbook.created = new Date()
  const sheet = workbook.addWorksheet('Inventory', { views: [{ state: 'frozen', ySplit: 1 }] })
  sheet.columns = [
    { header: 'Branch', key: 'branch_name', width: 22 },
    { header: 'Branch Code', key: 'branch_code', width: 15 },
    { header: 'Warehouse Code', key: 'branch_warehouse_code', width: 18 },
    { header: 'Device Type', key: 'device_type', width: 17 },
    { header: 'Model', key: 'model', width: 24 },
    { header: 'Name', key: 'name', width: 24 },
    { header: 'Hostname', key: 'hostname', width: 22 },
    { header: 'IP', key: 'ip', width: 17 },
    { header: 'Port', key: 'port', width: 10 },
    { header: 'Location', key: 'location', width: 22 },
    { header: 'Asset Code', key: 'asset_code', width: 20 },
    { header: 'Serial Number', key: 'serial_number', width: 22 },
    { header: 'Connection Type', key: 'connection_type', width: 18 },
    { header: 'Connection Port', key: 'connection_port', width: 18 },
    { header: 'ESXI Version', key: 'esxi_version', width: 16 },
    { header: 'Software Version', key: 'version', width: 18 },
    { header: 'User', key: 'user', width: 20 },
    { header: 'Domain', key: 'domain', width: 18 },
    { header: 'Checkout Number', key: 'checkout_number', width: 17 },
    { header: 'Brand', key: 'brand', width: 18 },
    { header: 'Terminal ID', key: 'terminal_id', width: 18 },
    { header: 'Acceptance ID', key: 'acceptance_id', width: 18 },
    { header: 'Switch Ports', key: 'switch_ports_summary', width: 48 },
    { header: 'Dashboard', key: 'dashboard_visibility', width: 13 },
    { header: 'Status', key: 'status', width: 12 },
    { header: 'Last Ping (ms)', key: 'ping_time', width: 15 }
  ]

  rows.forEach((row) => sheet.addRow({
    ...row,
    switch_ports_summary: formatSwitchPorts(row.switch_ports),
    dashboard_visibility: row.is_dashboard_visible ? 'Shown' : 'Hidden'
  }))

  sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }
  sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF5E81AC' } }
  sheet.getRow(1).alignment = { vertical: 'middle' }
  sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: Math.max(1, rows.length + 1), column: sheet.columnCount } }
  sheet.eachRow((row, rowNumber) => {
    row.alignment = { vertical: 'top', wrapText: rowNumber > 1 }
    if (rowNumber > 1 && rowNumber % 2 === 0) row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF4F6FA' } }
  })
  let filePath = outputPath
  if (!filePath) {
    const date = new Date().toISOString().slice(0, 10)
    const result = await dialog.showSaveDialog({
      title: 'Save inventory workbook',
      defaultPath: `Inventory_${clean(filters.branch)}_${clean(filters.type)}_${date}.xlsx`,
      filters: [{ name: 'Excel workbook', extensions: ['xlsx'] }]
    })
    if (result.canceled || !result.filePath) return { canceled: true }
    filePath = path.extname(result.filePath).toLowerCase() === '.xlsx' ? result.filePath : `${result.filePath}.xlsx`
  }

  await workbook.xlsx.writeFile(filePath)
  database.audit('Admin', 'INVENTORY_EXPORT', filePath, `${rows.length} devices exported`)
  return { success: true, path: filePath, count: rows.length }
}


module.exports = {
  BRANCH_HEADERS,
  DEVICE_HEADERS,
  PORT_HEADERS,
  DEVICE_TYPES,
  DEVICE_SHEET_FIELDS,
  MAX_SWITCH_PORTS,
  createImportTemplate,
  parseImportWorkbook,
  importDirectory,
  exportInventory
}
